[v1]
"cargo-binutils 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-as",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-edit 0.13.8 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-generate 0.23.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-list 0.33.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-list"]
"cargo-make 0.37.24 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-make",
    "makers",
]
"cargo-outdated 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-outdated"]
"cargo-update 18.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"just-lsp 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["just-lsp"]
"wasm-pack 0.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
